---
- name: "Enable http forwarder"
  ansible.builtin.file:
    src: "{{ nginx_dir }}/sites-available/{{ vhost.name }}.forward.conf"
    dest: "{{ nginx_dir }}/sites-enabled/{{ vhost.name }}.forward.conf"
    owner: "root"
    group: "root"
    state: "link"
  notify:
    - "Reload nginx"
  when:
    - "vhost.forward_http | default(false)"
    - "vhost.state | default(true)"

- name: "Enable service config"
  ansible.builtin.file:
    src: "{{ nginx_dir }}/sites-available/{{ vhost.name }}.conf"
    dest: "{{ nginx_dir }}/sites-enabled/{{ vhost.name }}.conf"
    owner: "root"
    group: "root"
    state: "link"
  notify:
    - "Reload nginx"
  when: "vhost.state | default(true)"

- name: "Disable forwarder config"
  ansible.builtin.file:
    path: "{{ nginx_dir }}/sites-enabled/{{ vhost.name }}.forward.conf"
    state: "absent"
  notify:
    - "Reload nginx"
  when: "not vhost.state | default(true)"

- name: "Disable config"
  ansible.builtin.file:
    path: "{{ nginx_dir }}/sites-enabled/{{ vhost.name }}.conf"
    state: "absent"
  notify:
    - "Reload nginx"
  when: "not vhost.state | default(true)"
...
