---
- name: "Install nginx"
  ansible.builtin.apt:
    name: "{{ nginx_package }}"
    state: "present"
  tags:
    - "nginx:init"
  notify:
    - "Enable nginx"

- name: "Disable default config"
  ansible.builtin.file:
    path: "{{ nginx_dir }}/sites-enabled/default"
    state: "absent"
  notify:
    - "Reload nginx"
  tags:
    - "nginx:init"

- name: "Install http to https forward"
  ansible.builtin.template:
    src: "templates/forward_http.conf.j2"
    dest: "{{ nginx_dir }}/sites-available/{{ item.name }}.forward.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ nginx_vhosts }}"
  when: "item.forward_http | default(false)"
  notify:
    - "Reload nginx"
  tags:
    - "nginx:config"

- name: "Install vhost configs"
  ansible.builtin.template:
    src: "templates/default.conf.j2"
    dest: "{{ nginx_dir }}/sites-available/{{ item.name }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ nginx_vhosts }}"
  notify:
    - "Reload nginx"
  tags:
    - "nginx:config"

- name: "Enable disable vhost config"
  ansible.builtin.include_tasks: "enable_disable_config.yaml"
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: "vhost"
  notify:
    - "Reload nginx"
  tags:
    - "ngnix:config"
...
