---
- name: 'install nginx'
  apt:
    name: '{{ role_nginx_package }}'
    state: 'present'
  tags:
    - 'never'
    - 'nginx:init'
  notify:
    - 'enable nginx'

- name: 'disable default config'
  file:
    path: '{{ role_nginx_dir }}/sites-enabled/default'
    state: 'absent'
  tags:
    - 'never'
    - 'nginx:init'

- name: 'install vhost config'
  template:
    src: 'templates/default.conf.j2'
    dest: '{{ role_nginx_dir }}/sites-available/{{ item.value.domain }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ role_nginx_vhosts|dict2items }}'
  notify:
    - 'reload nginx'
  tags:
    - 'nginx:config'

- name: 'enable disable vhost config'
  include_tasks: 'enable_disable_config.yaml'
  loop: '{{ role_nginx_vhosts|dict2items }}'
  loop_control:
    loop_var: 'vhosts'
  tags:
    - 'ngnix:config'
...
